// OK this is generated by an AI agent, I am too tired to check if the code is good or not..
const osloDateKeyFormatter = new Intl.DateTimeFormat("sv-SE", {
  timeZone: "Europe/Oslo",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
});

const osloDateTimeFormatter = new Intl.DateTimeFormat("nb-NO", {
  timeZone: "Europe/Oslo",
  day: "numeric",
  month: "short",
  year: "numeric",
  hour: "2-digit",
  minute: "2-digit",
});

const osloDateFormatter = new Intl.DateTimeFormat("nb-NO", {
  timeZone: "Europe/Oslo",
  day: "numeric",
  month: "short",
  year: "numeric",
});

const osloTimeFormatter = new Intl.DateTimeFormat("nb-NO", {
  timeZone: "Europe/Oslo",
  hour: "2-digit",
  minute: "2-digit",
});

export function isSameOsloDay(a: Date, b: Date) {
  return osloDateKeyFormatter.format(a) === osloDateKeyFormatter.format(b);
}

export function formatEventDateRange(start: Date, end: Date) {
  if (isSameOsloDay(start, end)) {
    return `${osloDateTimeFormatter.format(start)} - ${osloTimeFormatter.format(end)}`;
  }

  return `${osloDateTimeFormatter.format(start)} - ${osloDateFormatter.format(end)}`;
}
