CREATE TABLE "revetalhagenmk2_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revetalhagenmk2_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"type" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"description" text,
	"image" text
);
--> statement-breakpoint
CREATE TABLE "revetalhagenmk2_itemType" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revetalhagenmk2_itemType_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256)
);
--> statement-breakpoint
ALTER TABLE "revetalhagenmk2_item" ADD CONSTRAINT "revetalhagenmk2_item_type_revetalhagenmk2_itemType_id_fk" FOREIGN KEY ("type") REFERENCES "public"."revetalhagenmk2_itemType"("id") ON DELETE set null ON UPDATE no action;