CREATE TABLE "revetalhagenmk2_booking" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revetalhagenmk2_booking_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"item" integer,
	"email" text,
	"name" text NOT NULL,
	"phone" varchar(32),
	"from" timestamp with time zone NOT NULL,
	"to" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "revetalhagenmk2_booking" ADD CONSTRAINT "revetalhagenmk2_booking_item_revetalhagenmk2_item_id_fk" FOREIGN KEY ("item") REFERENCES "public"."revetalhagenmk2_item"("id") ON DELETE cascade ON UPDATE no action;