CREATE TABLE "revetalhagenmk2_itemMeta" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revetalhagenmk2_itemMeta_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"icon" text,
	"label" varchar(256),
	"item" integer
);
--> statement-breakpoint
ALTER TABLE "revetalhagenmk2_itemMeta" ADD CONSTRAINT "revetalhagenmk2_itemMeta_item_revetalhagenmk2_item_id_fk" FOREIGN KEY ("item") REFERENCES "public"."revetalhagenmk2_item"("id") ON DELETE cascade ON UPDATE no action;