CREATE TABLE "revetalhagenmk2_itemImage" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revetalhagenmk2_itemImage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"item" integer,
	"url" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "revetalhagenmk2_itemImage" ADD CONSTRAINT "revetalhagenmk2_itemImage_item_revetalhagenmk2_item_id_fk" FOREIGN KEY ("item") REFERENCES "public"."revetalhagenmk2_item"("id") ON DELETE cascade ON UPDATE no action;