CREATE TABLE "revetalhagenmk2_membership-application" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revetalhagenmk2_membership-application_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL,
	"phone" varchar(32) NOT NULL,
	CONSTRAINT "revetalhagenmk2_membership-application_email_unique" UNIQUE("email")
);
